### ISSUE TITLE
Relative datetime incorrect for old blocks

### ISSUE THREAD

**Issue by larrysalibra** [blockcypher/explorer#133]
Just noticed when filing #132 that the dates for old blocks all say 5 months 1 week ago.

Example: [Block 234][1] 

![screen shot 2015-04-29 at 7 14 18 pm](https://cloud.githubusercontent.com/assets/597182/7389782/fdbf43c2-eea3-11e4-8b05-19b61fa7c47a.png)
[1]: https://live.blockcypher.com/btc/block/234/

**Comment by mflaxman** [comment]
Thanks @larrysalibra!

@matthieu what's the best way to handle this?

https://api.blockcypher.com/v1/btc/main/blocks/234
```
{
  "hash": "00000000c2edc9f0ed8e33627247bbf78b89ee62b23ae48e6201debc28ff208e",
  "height": 234,
  "chain": "BTC.main",
  "total": 0,
  "fees": 0,
  "ver": 1,
  "time": "2009-01-12T17:08:14Z",
  "received_time": "2014-11-16T18:53:47.272Z",
  "bits": 486604799,
  "nonce": 2140423963,
  "n_tx": 1,
  "prev_block": "0000000016c7dad613635ae08f697c10935476b49dc67fdb6ef08b1143d01a3e",
  "mrkl_root": "0f00a4718228d0e7338695a96dba43dcf371cbe37d315395c8d60e516f5e5235",
  "txids": [
    "0f00a4718228d0e7338695a96dba43dcf371cbe37d315395c8d60e516f5e5235"
  ],
  "depth": 353984,
  "prev_block_url": "https://api.blockcypher.com/v1/btc/main/blocks/0000000016c7dad613635ae08f697c10935476b49dc67fdb6ef08b1143d01a3e",
  "tx_url": "https://api.blockcypher.com/v1/btc/main/txs/"
}
```

`time` is Jan 2009 (correct) but if I understand correctly that field can't really be trusted. `received_time` is in Nov 2014, which is technically correct but completely misleading to the end user.

Ideas:

1. I implement some basic logic like if block_num is < X, use `time` else use `received_time`, but if that's the case I need to know what the correct block_num is for each block explorer.
2. You add a field to the API called something like `best_guess_time` that does that for all API users and I switch to that.
3. Something else?

Obviously, I prefer choice 2 because it's less work for me, but it's also less work for everyone using the API so I think it's the best decision.

Assigning to you @matthieu to decide and I'll implement.

**Comment by matthieu** [comment]
Fixed it in the API. Practically people don't care about the different between block and receive time when it's more than a few days past. So the API now returns the block time for receive time for those older blocks that were issued before we pulled the block chain.
