### ISSUE TITLE
Need information about explorer

### ISSUE THREAD

**Issue by zekylaf** [blockcypher/explorer#152]
Hi, I wanna ask about pre-requisites. How much is the explorer size actually?

**Comment by mflaxman** [comment]
Hey @zekylaf, the explorer doesn't hold any of the blockchain in the local database and queries the blockcypher API on every single pageview. It would be theoretically possible to run this app without a database at all, but I'd need to make some config changes since currently the database is used for keeping track of user signups and some other things.

tl:dr; the size is close to 0.
