### ISSUE TITLE
Feature request: add an endpoint for getting the Nth transaction in the Mth block

### ISSUE THREAD

**Issue by shea256** [blockcypher/explorer#155]
#### Background

Every transaction within a block has a distinct order.

We at Onename are going to start using a transaction referencing system that uniquely identifies each transaction by its containing block number followed by the index of the transaction within that block.

It will look something like this: `374116-797` which is the 797th transaction within the block of height 374116.

Thus, adding a view/endpoint for viewing the details of the Nth transaction in the Mth block would be awesome.

#### Example endpoints

`https://live.blockcypher.com/btc/block/379793/796`
`https://live.blockcypher.com/btc/block/379793/tx/796`

**Comment by shea256** [comment]
@acityinohio mentioned that I should ping @mflaxman about this as well.

**Comment by matthieu** [comment]
While I'm not against the endpoint in general as it can be a useful way to reference a transaction, be careful if you plan to make this an internal id as it will change during chain reorgs.

**Comment by mflaxman** [comment]
@shea256 are you asking for an endpoint for the API (as in something that would be meant for computers and returns JSON) or you want a view on the block explorer to show it for humans (not for programmatic access)?

**Comment by mflaxman** [comment]
I think what @matthieu is saying is that this would be better identified as `00000000000000001238938da19b579b0d2e1c082b29cba035bc8a68c9cfa0d5-797` (block hash) vs `374116-797` (block height)

**Comment by acityinohio** [comment]
@mflaxman I think @shea256 was asking for both eventually (correct me if I'm wrong @shea256). Might be able to do it in the explorer without an endpoint; querying block endpoint for TXIDs then paging through results in array if need be...less efficient of course, might make more sense to wait for a direct endpoint instead. And @mflaxman/@matthieu's point is well taken, especially for recent blocks.

**Comment by matthieu** [comment]
Yeah, implementing that endpoint would only be 30 min so not a big deal. But yeah the issue with that:

https://live.blockcypher.com/btc/block/379793/tx/796

Is that it could flip flop between 2 different transactions (or even nothing if one of the two blocks have less txs) between reorgs.

**Comment by mflaxman** [comment]
Assigning to @matthieu to add an endpoint. I'll make a view once we have that.

**Comment by matthieu** [comment]
I'd like confirmation from @shea256 first on which is needed.

**Comment by shea256** [comment]
@matthieu to be clear, we are also using TXIDs to reference transactions. The block#-index# system is more of a human-parseable identifier that will be used as a longer-term identifier. As in, we're not concerned about reorgs because that's only a problem in the short term. Further, with our system, we have methods of making sure we're on the right chain.

@mflaxman I really just want a view on the block explorer (for humans). API endpoint would be nice as well but not the primary concern. The use-case is that each human will have an ID card that lists their block#-index# pair that their username was registered in. And we want them to be able to check a block explorer to ensure that they are seeing the right data.

**Comment by mflaxman** [comment]
@matthieu I just realized we already have an endpoint for this:
https://api.blockcypher.com/v1/btc/main/blocks/374116?txstart=796&limit=1
(`796` because it's 0-indexed for `797`)

What were you thinking of adding? Would be nice to be able to get the TX details in one API call (vs two), but that seems very low priority. One thing that would be nice would be very helpful, would be to be able to get the tx number (797 in this case) when querying the transaction:
https://api.blockcypher.com/v1/btc/main/txs/b924238993f1a4102d0bf3ea64746df83daa08415b9ad7a49e8e294099351050

The only way to get that now is to paginate through all the TXs in the block to find it, which is *really* expensive.

**Comment by mflaxman** [comment]
@shea256 gotcha, that makes sense and is quite straightforward.

Re the URL structure, there already is a canonical page for that transaction:
https://live.blockcypher.com/btc/tx/b924238993f1a4102d0bf3ea64746df83daa08415b9ad7a49e8e294099351050/

It's trivial to make a new URL like one of the two you suggested (https://live.blockcypher.com/btc/block/379793/796 or https://live.blockcypher.com/btc/block/379793/tx/796) and have it redirect to the canonical page, but I don't know if that helps your users? Some things I could do in addition:
- Add some copy on the "Advanced Details" with the transaction # in that block (assuming @matthieu adds that to the endpoint re my previous comment), which gives you the info but is a bit buried
- Add some sort of UI-callout for it at the top of the page IFF you've been redirected from that special URL. Probably I'd do this by appending something like #show-tx-num-in-block or ?show-tx-num-in-block=True to the URL.

It's possible to create a view with duplicate content, but I'm hesitant to do this for multiple reasons:
1) It's bad SEO. This can be fixed with `rel=canonical`, but I'm afraid of that tag. There are horror stories of people mis-using it and destroying their SEO.
2) It feels sloppy.

**Comment by shea256** [comment]
I like the idea of adding a UI element to the page that indicates the index
of the transaction within the block. And then if one lands on the page from
the redirect this will be more prominently displayed right?

-- 

*RYAN SHEA*   *CO-FOUNDER, ONENAME*

*onename.com/ryan <https://onename.com/ryan>*

*650-564-7432 <650-564-7432>*

**Comment by matthieu** [comment]
The index of a transaction within a block is something we already store on the backend, with the transaction. We don't return it in the API yet as no one has cared so far but we could add it easily with pretty much no performance penalty (except the extra bytes).

**Comment by mflaxman** [comment]
Actually @matthieu, it's not crazy expensive because I don't have to paginate. I can get it in one call:
https://api.blockcypher.com/v1/btc/main/blocks/374116?limit=999999

That said, it's two API calls on the transaction page vs just one currently. It  doesn't seem worth it to double the # of API calls on the page if it's easy for you to return the index. Can you add to the existing tx endpoint?

**Comment by mflaxman** [comment]
@shea256 what do you think of this?
https://live.blockcypher.com/btc/block/374116/796/

I'm closing this as it works now, although it could definitely be better (my design skills are weak).

I've opened a new ticket for to add "TX Index in Block" to Advanced Details of Transaction Page:
https://github.com/blockcypher/explorer/issues/156

**Comment by mflaxman** [comment]
@shea256  there's an even newer/better version (specified in #156)... What do you think?

https://live.blockcypher.com/btc/block/374116/796/

(I couldn't @ mention you on that issue I suppose since you're not subscribed to this repo.)

**Comment by shea256** [comment]
OK commented in the other thread. Quick question - will someone know that "transaction 796" is really the 797th transaction AKA number 796 on an index that starts at zero? I think the answer is yes but just want to double confirm.

**Comment by mflaxman** [comment]
Hmm, I'm not sure. What do you think? It's trivial for me to alter it by 1. And/or I could add some copy that explains it's 0-indexed.

Open to whatever, yours is so far the only use-case I'm aware of.
