### ISSUE TITLE
Showing a confirmed amount of bitcoin but the majority is not in my wallet. Not being able to make transactions either

### ISSUE THREAD

**Issue by D2301** [blockcypher/explorer#214]
On blockcypher im being shown an amount of bitcoin as confirmed and final but theres over .04 missing in my wallet. It could be that i made a transaction using those but there is no transaction showing up for those coins. Also im not being able to make transactions keep getting many various errors that have no reasoning to pop up.

**Comment by R4175** [comment]
My btc 0.01 not send in my account last 20 days how it problem.. unconform see it why plz help

**Comment by sakukurata** [comment]
Help me



Pada tanggal 29 Des 2017 15.36, "R4175" <notifications@github.com> menulis:

**Comment by R4175** [comment]
No i have no receive this btc..i check notification and see uncomform this i have a picture in uncomform this time

**Comment by R4175** [comment]
I have no receive this btc..this screen shot time is today

On Dec 30, 2017 8:10 AM, rihankhan4175.rk@gmail.com wrote:


On Dec 29, 2017 8:10 PM, "sakukurata" <notifications@github.com> wrote:

Help me



Pada tanggal 29 Des 2017 15.36, "R4175" <notifications@github.com> menulis:

> My btc 0.01 not send in my account last 20 days how it problem.. unconform
> see it why plz help
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/blockcypher/explorer/issues/214#issuecomment-354415971
>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-
auth/AhL3gok9lyKrFXi63D7NkEr-MXSMPELIks5tFKSpgaJpZM4Q78Bw>
> .
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/blockcypher/explorer/issues/214#issuecomment-354454128>,
or mute the thread

**Comment by prasadkarpe** [comment]
975401a100e226c5ab620f8096260e6264843c144a626b71fcdacecc30a0245a my transaction is not found.. i sent 0.002 btc.. pls help

**Comment by higer44** [comment]
hello me too i dont recieve  mu dog coin zhat is the mater here

**Comment by R4175** [comment]
30dc884e3db592542a91922e9b76a0a7ce767276fdd1194621c0fb230f8f2cd1.  This address send me 0.01 btc uncomform see it last 15days why pl help.. me

**Comment by R4175** [comment]
30dc884e3db592542a91922e9b76a0a7ce767276fdd1194621c0fb230f8f2cd1.....this
image is today plz help and send my account plzzz

**Comment by R4175** [comment]
And my btc address is....3EqymSCADgzNh6ahV1sEBXgYihbWaesFvW....you check
blockcypher this address plzzz help
